# 线代其余五章：子 agent 题图标注 → overlay 行
# 每行: id, kp_ids, facets（逗号分隔）
ROWS = r"""
ll-base-10-big-1	la.det.compute	det_compute,det_prop
ll-base-10-big-2	la.det.compute	rec_expand,det_compute
ll-base-10-big-3	la.det.compute	rec_expand,cofactor,det_compute
ll-base-10-fill-1	la.det.compute	det_compute,det_prop
ll-base-10-fill-2	la.det.compute	det_compute
ll-base-10-fill-3	la.det.compute	det_compute
ll-base-10-fill-4	la.det.compute	det_compute,cofactor
ll-base-10-fill-5	la.det.def	det_def,poly_coeff
ll-base-10-fill-6	la.det.def	det_prop
ll-base-10-fill-7	la.det.def	det_prop
ll-base-10-fill-8	la.det.def	det_prop
ll-base-10-fill-9	la.det.compute	adjoint_det,det_prop
ll-base-10-fill-10	la.det.def	det_prop
ll-base-10-fill-11	la.det.cofactor	cofactor
ll-base-10-mcq-1	la.det.cofactor	cofactor
ll-base-10-mcq-2	la.det.def	det_prop
ll-base-10-mcq-3	la.det.cofactor,la.det.compute	adjoint_det,cofactor
ll-hard-10-big-1	la.det.compute	det_compute,det_prop
ll-hard-10-big-1-x2	la.det.compute	adjoint_det,det_prop
ll-hard-10-big-2	la.det.compute	det_compute,det_prop
ll-hard-10-big-2-x2	la.det.compute,la.mat.inv	adjoint_det,det_prop
ll-hard-10-big-3	la.det.compute	rec_expand,cofactor
ll-hard-10-big-4	la.det.compute	rec_expand
ll-hard-10-fill-1	la.det.compute	block_det,adjoint_det
ll-hard-10-fill-2	la.det.compute,la.mat.inv	det_prop,det_compute
ll-hard-10-fill-3	la.det.compute,la.eig.value	adjoint_det,eig_det
ll-hard-10-fill-4	la.det.compute	det_prop
ll-hard-10-fill-5	la.det.compute	det_prop
ll-hard-10-fill-6	la.det.cofactor	cofactor,adjoint_det
ll-hard-10-mcq-1	la.det.cofactor,la.eig.value	cofactor,adjoint_det,eig_det
ll-hard-10-mcq-2	la.det.compute	adjoint_det,det_prop
ll-hard-10-mcq-3	la.det.compute	vandermonde,det_compute
zy-base-la-1-2	la.det.def	det_def,det_prop
zy-base-la-1-7	la.det.compute,la.mat.rank	cofactor,det_compute
zy-base-la-1-9	la.det.cofactor	cofactor
zy-base-la-1-10	la.det.compute	det_compute,rec_expand,det_prop
zy-base-la-1-11	la.det.compute	det_prop
zy-base-la-1-1	la.det.def	det_prop,det_compute
zy-base-la-1-3	la.det.def	det_def
zy-base-la-1-4	la.det.def	det_prop
zy-base-la-1-5	la.det.compute	det_compute,calc_mixed
zy-base-la-1-6	la.det.compute	rec_expand
zy-hard-la-1-1	la.det.compute	det_compute,det_prop
zy-hard-la-1-2	la.det.compute	rec_expand,cofactor
zy-hard-la-1-5	la.eig.diag,la.det.compute	eig_det
zy-hard-la-1-7	la.eig.value	eig_det
zy-hard-la-1-3	la.det.compute,la.eig.similar	block_det,adjoint_det,eig_det
zy-hard-la-1-4	la.det.compute	det_prop
zy-hard-la-1-6	la.det.compute,la.eig.value	eig_det,det_compute
zy-hard-la-2-3	la.det.cofactor	cofactor
zy-hard-la-2-4	la.det.cofactor	cofactor,adjoint_det
zy-hard-la-2-2	la.det.cofactor	cofactor
zy-hard-la-2-1	la.det.cofactor	cofactor
ll-base-11-big-1	la.mat.rank,la.mat.ops	rank,mat_ops,poly_mat
ll-base-11-big-2	la.mat.inv	inverse,mat_ops
ll-base-11-big-3	la.mat.inv	inverse,adjoint
ll-base-11-big-4	la.mat.inv	inverse,poly_mat
ll-base-11-big-5	la.mat.inv	inverse
ll-base-11-big-6	la.mat.inv,la.sp.ortho	inverse,ortho_mat
ll-base-11-big-7	la.mat.inv	inverse,poly_mat
ll-base-11-big-8	la.mat.inv	mat_eq,inverse
ll-base-11-big-9	la.mat.inv	mat_eq,inverse
ll-base-11-big-10	la.mat.inv	mat_eq,inverse
ll-base-11-big-11	la.mat.ops	mat_eq
ll-base-11-fill-1	la.mat.ops	mat_ops,poly_mat
ll-base-11-fill-2	la.mat.ops	mat_ops,poly_mat
ll-base-11-fill-3	la.mat.ops	mat_ops,poly_mat
ll-base-11-fill-4	la.mat.ops	mat_ops,poly_mat
ll-base-11-fill-5	la.mat.ops	mat_ops,poly_mat
ll-base-11-fill-6	la.mat.inv,la.det.compute	adjoint,inverse,elem_trans
ll-base-11-fill-7	la.mat.inv	inverse,poly_mat
ll-base-11-fill-8	la.mat.inv	adjoint,inverse
ll-base-11-fill-9	la.mat.inv	inverse,poly_mat
ll-base-11-fill-10	la.mat.inv	inverse,mat_ops
ll-base-11-fill-11	la.mat.inv,la.det.compute	inverse,adjoint,elem_trans
ll-base-11-mcq-1	la.mat.ops	elem_trans
ll-base-11-mcq-2	la.mat.inv	adjoint,inverse
ll-base-11-mcq-3	la.mat.inv,la.det.compute	adjoint,inverse
ll-base-11-mcq-4	la.mat.rank	rank,elem_trans
ll-base-11-mcq-5	la.det.def	elem_trans,det_prop
ll-base-11-mcq-6	la.mat.rank,la.mat.inv	rank,adjoint,block
ll-hard-11-big-1	la.mat.ops	mat_ops,poly_mat
ll-hard-11-big-1-x2	la.mat.inv	mat_eq,inverse
ll-hard-11-big-2	la.mat.inv	inverse,poly_mat,mat_ops
ll-hard-11-big-2-x2	la.mat.inv,la.sp.ortho	block,inverse,ortho_mat
ll-hard-11-big-3	la.mat.inv	adjoint,mat_eq,inverse
ll-hard-11-big-4	la.mat.inv	mat_eq,inverse
ll-hard-11-fill-1	la.mat.inv	adjoint,block
ll-hard-11-fill-2	la.mat.inv	inverse
ll-hard-11-fill-3	la.mat.ops	mat_ops,poly_mat
ll-hard-11-fill-4	la.mat.inv	inverse,poly_mat
ll-hard-11-fill-5	la.mat.rank,la.mat.inv	rank_ineq,inverse,poly_mat
ll-hard-11-fill-6	la.mat.inv	adjoint,inverse
ll-hard-11-mcq-1	la.mat.rank	rank,rank_ineq
ll-hard-11-mcq-2	la.mat.rank,la.mat.inv	rank,adjoint
ll-hard-11-mcq-3	la.mat.ops	elem_trans,mat_ops
ll-hard-11-mcq-4	la.mat.rank	rank_ineq,block,elem_trans
ll-hard-11-mcq-5	la.mat.rank	rank_ineq,block
ll-hard-11-mcq-6	la.mat.inv	inverse
ll-hard-11-mcq-7	la.mat.inv	inverse,adjoint,elem_trans
zy-base-la-2-1	la.mat.ops	mat_ops
zy-base-la-2-2	la.mat.ops	mat_ops
zy-base-la-2-3	la.mat.ops	mat_ops
zy-base-la-2-4	la.mat.inv	inverse,poly_mat
zy-base-la-2-5	la.mat.inv	inverse,mat_eq
zy-base-la-2-6	la.mat.inv,la.det.compute	adjoint,inverse,block
zy-base-la-2-7	la.mat.inv	adjoint,block
zy-base-la-2-8	la.mat.inv,la.det.compute	inverse,adjoint
zy-base-la-2-9	la.mat.ops,la.mat.inv	elem_trans,inverse
zy-base-la-2-10	la.mat.ops	elem_trans
zy-base-la-2-11	la.mat.ops,la.mat.rank	elem_trans,rank
zy-base-la-2-12	la.mat.ops	elem_trans
zy-base-la-2-13	la.mat.ops	elem_trans
zy-base-la-2-14	la.mat.rank	rank,rank_ineq
zy-base-la-2-15	la.mat.rank	rank,rank_ineq,mat_eq
zy-base-la-2-16	la.sp.ortho	mat_ops,ortho_mat
zy-base-la-2-17	la.mat.inv	inverse,poly_mat
zy-base-la-2-18	la.mat.ops	poly_mat
zy-base-la-2-19	la.mat.rank,la.mat.inv	rank,adjoint,rank_ineq
zy-hard-la-3-1	la.mat.ops	mat_ops
zy-hard-la-3-2	la.mat.ops	mat_ops,poly_mat
zy-hard-la-3-4	la.mat.ops,la.mat.inv	mat_eq,mat_ops,inverse
zy-hard-la-3-5	la.mat.ops,la.eig.value	poly_mat
zy-hard-la-3-6	la.mat.ops,la.mat.inv	mat_ops,inverse,adjoint
zy-hard-la-3-7	la.eig.similar,la.eig.value	mat_eq
zy-hard-la-3-8	la.mat.inv	block,adjoint,inverse
zy-hard-la-3-9	la.mat.ops	mat_ops
zy-hard-la-3-10	la.mat.ops	mat_eq
zy-hard-la-4-1	la.mat.rank	rank,rank_ineq
zy-hard-la-4-2	la.mat.rank,la.mat.inv	rank,adjoint,rank_ineq
zy-hard-la-4-3	la.mat.rank	rank
zy-hard-la-4-4	la.mat.rank	rank_ineq
zy-hard-la-4-6	la.mat.rank	rank_ineq,block
zy-hard-la-4-7	la.mat.rank	rank_ineq,block
zy-hard-la-4-8	la.mat.rank	rank
ll-base-12-big-1	la.eq.vector	vector_rank,max_ind,represent
ll-base-12-big-2	la.eq.vector	max_ind,represent
ll-base-12-big-3	la.eq.vector	represent
ll-base-12-big-4	la.eq.vector	vector_rank,represent
ll-base-12-big-5	la.eq.vector	equiv
ll-base-12-big-6	la.eq.vector	vector_rank
ll-base-12-big-7	la.eq.vector,la.eig.value	dep
ll-base-12-big-8	la.sp.ortho,la.eq.structure	schmidt
ll-base-12-fill-1	la.eq.vector	dep
ll-base-12-fill-2	la.sp.basis	basis
ll-base-12-fill-3	la.sp.basis	transition
ll-base-12-mcq-1	la.eq.vector	dep,represent
ll-base-12-mcq-2	la.eq.vector	dep,represent
ll-base-12-mcq-3	la.eq.vector	dep
ll-base-12-mcq-4	la.eq.vector	represent,dep
ll-base-12-mcq-5	la.eq.vector	vector_rank
ll-base-12-mcq-6	la.eq.vector	dep
ll-hard-12-big-1	la.eq.vector,la.mat.ops	max_ind
ll-hard-12-big-2	la.eq.vector	represent
ll-hard-12-big-3	la.eq.vector,la.eig.value	dep
ll-hard-12-big-4	la.eq.vector	represent
ll-hard-12-big-5	la.eq.vector,la.mat.ops	max_ind,represent
ll-hard-12-big-6	la.sp.ortho,la.mat.ops	schmidt,ortho_mat
ll-hard-12-big-7	la.sp.basis	transition,basis
ll-hard-12-fill-1	la.eq.vector	dep
ll-hard-12-fill-2	la.eq.vector	represent
ll-hard-12-fill-3	la.sp.basis	basis
ll-hard-12-mcq-1	la.eq.vector	dep
ll-hard-12-mcq-2	la.eq.vector	dep
ll-hard-12-mcq-3	la.eq.vector	equiv,represent
ll-hard-12-mcq-4	la.eq.vector	dep,equiv
ll-hard-12-mcq-5	la.sp.ortho	inner
ll-hard-12-mcq-6	la.eq.common	common_same
ll-hard-12-mcq-7	la.eq.vector,la.mat.ops	equiv
ll-hard-12-mcq-8	la.eq.vector	equiv
zy-base-la-3-1	la.eq.vector	dep,represent
zy-base-la-3-2	la.eq.vector	dep
zy-base-la-3-3	la.eq.vector	dep,represent
zy-base-la-3-4	la.eq.vector,la.mat.rank	dep,vector_rank
zy-base-la-3-5	la.eq.vector	dep,represent
zy-base-la-3-6	la.eq.vector	dep
zy-base-la-3-7	la.eq.vector	dep
zy-base-la-3-9	la.eq.vector	dep
zy-base-la-3-10	la.eq.vector	dep,represent
zy-base-la-3-11	la.eq.vector	equiv
zy-base-la-3-12	la.eq.vector	equiv
zy-hard-la-6-1	la.eq.vector	dep
zy-hard-la-6-2	la.eq.vector	equiv
zy-hard-la-6-3	la.eq.vector	represent
zy-hard-la-6-4	la.eq.vector	max_ind,represent
zy-hard-la-6-5	la.eq.vector	equiv,represent
zy-hard-la-6-6	la.eq.vector	represent
zy-hard-la-6-7	la.eq.vector	represent
zy-hard-la-6-8	la.sp.basis	basis
zy-hard-la-6-9	la.sp.basis	basis
zy-hard-la-6-10	la.sp.basis	transition
zy-hard-la-6-11	la.sp.ortho	schmidt,basis
""".strip()

ROWS2 = r"""
ll-base-14-big-1	la.eig.diag,la.eig.value	eigen_compute,diagonalize,real_sym
ll-base-14-big-2	la.eig.similar	similar,eigen_compute
ll-base-14-big-3	la.eig.diag,la.eig.value	eigen_compute,diagonalize
ll-base-14-big-4	la.eig.diag,la.eig.value	diagonalize,eigen_compute
ll-base-14-big-5	la.eig.diag,la.eig.value	eigen_compute,diagonalize,eigen_prop
ll-base-14-big-6	la.eig.diag,la.eig.similar	real_sym,eigen_compute,diagonalize
ll-base-14-big-7	la.eig.similar,la.eig.diag	similar,diagonalize,eigen_compute
ll-base-14-big-8	la.eig.similar,la.eig.diag	similar,real_sym
ll-base-14-big-9	la.eig.value,la.eig.diag	eigen_prop,diagonalize
ll-base-14-big-10	la.eig.value,la.eig.similar	eigen_compute,similar
ll-base-14-fill-1	la.eig.value	eigen_prop,cayley
ll-base-14-fill-2	la.eig.value	eigen_prop
ll-base-14-fill-3	la.eig.value	real_sym,eigen_compute,eigen_prop
ll-base-14-fill-4	la.eig.similar,la.eig.value	similar,eigen_prop
ll-base-14-mcq-1	la.eig.value	eigen_prop
ll-base-14-mcq-2	la.eig.diag,la.eig.similar	diagonalize,similar
ll-base-14-mcq-3	la.eig.diag	diagonalize
ll-base-14-mcq-4	la.eig.similar	similar
ll-base-14-mcq-5	la.eig.value	eigen_prop
ll-base-14-mcq-6	la.eig.value	eigen_prop
ll-hard-14-big-1	la.eig.diag,la.eig.value	diagonalize,eigen_compute
ll-hard-14-big-1-x2	la.eig.value,la.eig.diag	real_sym,eigen_compute,eigen_prop
ll-hard-14-big-2	la.eig.similar,la.eig.value	similar,eigen_compute,jordan
ll-hard-14-big-2-x2	la.eig.diag,la.eig.value	diagonalize,eigen_compute,recurrence
ll-hard-14-big-3	la.eig.value	eigen_prop,similar,jordan
ll-hard-14-big-4	la.eig.value	eigen_prop,jordan
ll-hard-14-big-5	la.eig.value,la.eig.diag	eigen_prop,diagonalize
ll-hard-14-big-6	la.eig.diag,la.eig.value	diagonalize,eigen_compute
ll-hard-14-big-7	la.eig.diag,la.eig.value	diagonalize,real_sym,eigen_compute
ll-hard-14-big-8	la.eig.diag	diagonalize
ll-hard-14-big-9	la.eig.diag	diagonalize,real_sym
ll-hard-14-big-10	la.eig.diag,la.eig.value	real_sym,diagonalize,eigen_compute
ll-hard-14-big-11	la.eig.diag	real_sym,diagonalize
ll-hard-14-big-12	la.eig.similar,la.eig.diag	similar,real_sym,diagonalize
ll-hard-14-big-13	la.eig.diag,la.eig.value	eigen_prop,diagonalize
ll-hard-14-big-14	la.eig.diag,la.eig.value	real_sym,diagonalize
ll-hard-14-big-15	la.eig.diag,la.eig.value	diagonalize,eigen_compute
ll-hard-14-big-16	la.eig.similar,la.eig.diag	similar,eigen_compute,eigen_prop
ll-hard-14-big-17	la.eig.diag	diagonalize,eigen_prop
ll-hard-14-fill-1	la.eig.value,la.eig.diag	eigen_prop,diagonalize
ll-hard-14-fill-2	la.eig.value	real_sym,eigen_compute
ll-hard-14-fill-3	la.eig.value	eigen_prop,real_sym
ll-hard-14-mcq-1	la.eig.similar	similar
ll-hard-14-mcq-2	la.eig.similar,la.eig.diag	similar,real_sym,eigen_prop
ll-hard-14-mcq-3	la.eig.similar,la.eig.quad	similar,real_sym
ll-hard-14-mcq-4	la.eig.similar	similar,jordan
ll-hard-14-mcq-5	la.eig.value	eigen_prop
ll-hard-14-mcq-6	la.eig.value	real_sym,eigen_compute
ll-hard-14-mcq-7	la.eig.value,la.eig.diag	eigen_prop,diagonalize
ll-hard-14-mcq-8	la.eig.diag,la.eig.similar	diagonalize,similar
ll-hard-14-mcq-9	la.eig.value	eigen_prop
ll-hard-14-mcq-10	la.eig.diag	diagonalize
zy-base-la-5-1	la.eig.value	eigen_prop
zy-base-la-5-2	la.eig.diag,la.eig.value	diagonalize,eigen_compute
zy-base-la-5-3	la.eig.diag	diagonalize
zy-base-la-5-4	la.eig.value	eigen_prop
zy-base-la-5-5	la.eig.value,la.eig.similar	eigen_prop,similar
zy-base-la-5-6	la.eig.value,la.eig.similar	eigen_compute,similar
zy-base-la-5-7	la.eig.diag	diagonalize
zy-base-la-5-8	la.eig.diag,la.eig.value	diagonalize,eigen_compute
zy-base-la-5-9	la.eig.diag	diagonalize,eigen_prop
zy-base-la-5-10	la.eig.diag,la.eig.value	diagonalize,eigen_compute
zy-base-la-5-11	la.eig.diag,la.eig.value	diagonalize,eigen_compute
zy-base-la-5-12	la.eig.diag,la.eig.value	real_sym,diagonalize
zy-base-la-5-13	la.eig.value,la.eig.diag	eigen_prop,real_sym,cayley
zy-base-la-5-14	la.eig.similar,la.eig.value	similar,eigen_prop
zy-base-la-5-15	la.eig.diag,la.eig.value	diagonalize,eigen_compute
zy-base-la-5-16	la.eig.diag	diagonalize
zy-base-la-5-17	la.eig.value	eigen_prop
zy-base-la-5-18	la.eig.value	cayley,eigen_prop
zy-base-la-5-19	la.eig.similar	similar
zy-base-la-5-20	la.eig.value	eigen_prop
zy-base-la-5-21	la.eig.value	eigen_compute,eigen_prop
zy-base-la-5-22	la.eig.value	eigen_prop
zy-base-la-5-23	la.eig.diag,la.eig.value	real_sym,diagonalize
zy-hard-la-7-1	la.eig.value	eigen_compute,eigen_prop
zy-hard-la-7-2	la.eig.diag,la.eig.value	diagonalize,eigen_compute
zy-hard-la-7-3	la.eig.value,la.eq.structure	eigen_prop,structure
zy-hard-la-7-4	la.eig.diag	diagonalize
zy-hard-la-7-5	la.eig.value	eigen_compute,eigen_prop
zy-hard-la-7-6	la.eig.diag,la.eig.value	diagonalize,eigen_compute
zy-hard-la-7-7	la.eig.diag,la.eig.value	diagonalize,eigen_prop
zy-hard-la-7-8	la.eig.value	eigen_prop
zy-hard-la-7-9	la.eig.diag,la.eig.value	diagonalize,eigen_compute
zy-hard-la-8-1	la.eig.diag	diagonalize,eigen_prop
zy-hard-la-8-2	la.eig.diag	diagonalize
zy-hard-la-8-3	la.eig.similar	similar
zy-hard-la-8-4	la.eig.similar	similar
zy-hard-la-8-5	la.eig.similar,la.eig.value	similar,jordan
zy-hard-la-8-6	la.eig.diag	diagonalize
zy-hard-la-8-7	la.eig.diag,la.eig.value	diagonalize,eigen_compute
zy-hard-la-8-8	la.eig.diag,la.eig.value	diagonalize,eigen_compute
zy-hard-la-8-9	la.eig.similar,la.eig.diag	similar,diagonalize
zy-hard-la-8-10	la.eig.diag,la.eig.similar	diagonalize,similar
zy-hard-la-8-11	la.eig.similar	similar
zy-hard-la-8-12	la.eig.similar,la.mat.rank	similar
zy-hard-la-8-13	la.eig.diag,la.eig.value	real_sym,eigen_prop
zy-hard-la-8-14	la.eig.diag	real_sym
zy-hard-la-8-15	la.eig.diag,la.eig.value	real_sym,diagonalize
zy-hard-la-8-16	la.eig.value,la.eig.similar	eigen_compute,similar,cayley
zy-hard-la-8-17	la.eig.diag	diagonalize
zy-hard-la-8-18	la.eig.similar,la.eig.value	similar,jordan
zy-hard-la-8-19	la.eig.diag,la.eig.value	real_sym,diagonalize,eigen_compute
zy-hard-la-8-20	la.eig.diag,la.eig.value	diagonalize,eigen_compute
zy-hard-la-8-21	la.eig.diag,la.eig.value	diagonalize,eigen_prop
ll-base-15-big-1	la.eig.quad	ortho_trans,complete_square
ll-base-15-big-2	la.eig.quad	ortho_trans
ll-base-15-big-3	la.eig.quad	congruent,inertia,ortho_trans
ll-base-15-big-4	la.eig.quad	complete_square,ortho_trans,inertia
ll-base-15-big-5	la.eig.quad	ortho_trans
ll-base-15-big-6	la.eig.quad,la.eig.pd	inertia,pd_complete
ll-base-15-fill-1	la.eig.pd	pd,quad_matrix
ll-base-15-fill-2	la.eig.quad	ortho_trans
ll-base-15-mcq-1	la.eig.quad	complete_square,inertia
ll-base-15-mcq-2	la.eig.quad	congruent
ll-base-15-mcq-3	la.eig.quad	congruent
ll-base-15-mcq-4	la.eig.quad	inertia
ll-base-15-mcq-5	la.eig.pd	pd,congruent
ll-base-15-mcq-6	la.eig.quad	congruent
ll-base-15-mcq-7	la.eig.quad	congruent,inertia
ll-base-15-mcq-8	la.eig.quad	inertia
ll-base-15-mcq-9	la.eig.quad	inertia,quadric
ll-base-15-mcq-10	la.eig.pd	pd,quadric
ll-hard-15-big-1	la.eig.quad	inertia,complete_square
ll-hard-15-big-1-x2	la.eig.quad	quad_rank,inertia
ll-hard-15-big-2	la.eig.quad	ortho_trans
ll-hard-15-big-2-x2	la.eig.quad	ortho_trans
ll-hard-15-big-3	la.eig.pd	pd
ll-hard-15-big-3-x2	la.eig.quad,la.eig.pd	ortho_trans,pd_complete
ll-hard-15-big-4	la.eig.quad	congruent,inertia,ortho_trans
ll-hard-15-big-4-x2	la.eig.quad	congruent,ortho_trans
ll-hard-15-big-5	la.eig.quad	ortho_trans
ll-hard-15-big-5-x2	la.eig.quad	ortho_trans
ll-hard-15-big-6	la.eig.quad,la.eig.pd	ortho_trans,pd
ll-hard-15-big-7	la.eig.quad	quad_eq
ll-hard-15-big-8	la.eig.quad,la.eig.pd	ortho_trans,pd
ll-hard-15-big-9	la.eig.quad	congruent,inertia,rayleigh
ll-hard-15-big-10	la.eig.quad	ortho_trans
ll-hard-15-big-11	la.eig.quad,la.eig.pd	pd,congruent
ll-hard-15-big-12	la.eig.quad,la.eig.pd	ortho_trans,pd_complete
ll-hard-15-fill-1	la.eig.pd	pd,inertia
ll-hard-15-fill-2	la.eig.quad	inertia
ll-hard-15-fill-3	la.eig.quad	rayleigh
ll-hard-15-mcq-1	la.eig.quad	inertia
ll-hard-15-mcq-2	la.eig.quad	inertia,quadric
ll-hard-15-mcq-3	la.eig.quad	congruent
ll-hard-15-mcq-4	la.eig.quad	inertia
ll-hard-15-mcq-5	la.eig.quad	congruent
ll-hard-15-mcq-6	la.eig.pd	pd
ll-hard-15-mcq-7	la.eig.quad	congruent,quad_rank
ll-hard-15-mcq-8	la.eig.quad,la.eig.pd	pd,inertia
ll-hard-15-mcq-9	la.eig.quad	inertia
ll-hard-15-mcq-10	la.eig.quad	inertia
ll-hard-15-mcq-11	la.eig.quad	inertia
ll-hard-15-mcq-12	la.eig.pd	pd
zy-base-la-6-1	la.eig.quad	inertia
zy-base-la-6-2	la.eig.quad	inertia
zy-base-la-6-3	la.eig.quad	quad_rank
zy-base-la-6-4	la.eig.quad	ortho_trans
zy-base-la-6-5	la.eig.quad	ortho_trans
zy-base-la-6-6	la.eig.quad	inertia
zy-base-la-6-7	la.eig.quad,la.eig.similar	ortho_trans,congruent
zy-base-la-6-8	la.eig.quad,la.eig.similar	congruent
zy-base-la-6-9	la.eig.quad,la.eig.similar	congruent
zy-base-la-6-10	la.eig.pd	pd
zy-base-la-6-11	la.eig.pd,la.eig.quad	pd,congruent
zy-base-la-6-12	la.eig.pd,la.eig.value	pd
zy-base-la-6-13	la.eig.quad,la.eq.structure	ortho_trans
zy-base-la-6-15	la.eig.quad	congruent,inertia
zy-base-la-6-16	la.eig.quad,la.eig.value	rayleigh
zy-base-la-6-17	la.eig.quad	inertia
zy-base-la-6-18	la.eig.quad	congruent
zy-base-la-6-19	la.eig.quad	congruent
zy-base-la-6-20	la.eig.quad,la.eig.value	ortho_trans
zy-base-la-6-21	la.eig.quad,la.eig.similar	congruent
zy-base-la-6-22	la.eig.pd	pd
zy-base-la-6-23	la.eig.quad	ortho_trans,rayleigh
zy-base-la-6-24	la.eig.quad	ortho_trans
zy-base-la-6-25	la.eig.pd	pd
zy-base-la-6-26	la.eig.quad,calc.geom.quad	inertia,quadric
zy-base-la-6-27	la.eig.quad,calc.geom.quad	ortho_trans,quadric
zy-hard-la-9-1	la.eig.quad	congruent,inertia
zy-hard-la-9-2	la.eig.quad,la.eig.value	inertia
zy-hard-la-9-3	la.eig.quad	inertia
zy-hard-la-9-4	la.eig.quad	inertia
zy-hard-la-9-5	la.eig.quad	inertia,quad_matrix
zy-hard-la-9-6	la.eig.quad	inertia
zy-hard-la-9-7	la.eig.quad,la.eig.value	eigen_prop
zy-hard-la-9-8	la.eig.quad	quad_rank
zy-hard-la-9-9	la.eig.quad	quad_rank
zy-hard-la-9-11	la.eig.quad,calc.geom.quad	ortho_trans,quadric
zy-hard-la-9-12	la.eig.quad	ortho_trans,rayleigh
zy-hard-la-9-13	la.eig.quad,la.eig.pd	ortho_trans,pd_complete
zy-hard-la-9-14	la.eig.quad	ortho_trans
zy-hard-la-9-15	la.eig.pd,la.eig.quad	pd_complete,rayleigh
zy-hard-la-9-16	la.eig.quad	congruent
zy-hard-la-9-17	la.eig.quad	congruent
zy-hard-la-9-18	la.eig.quad	simultaneous
zy-hard-la-9-19	la.eig.pd,la.eig.quad	pd
zy-hard-la-9-20	la.eig.pd	pd
zy-hard-la-9-21	la.eig.pd	pd_complete
zy-hard-la-9-22	la.eig.pd	pd
zy-hard-la-9-23	la.eig.pd,la.eig.quad	pd,inertia
zy-hard-la-9-24	la.eig.pd,la.sp.ortho	pd
zy-hard-la-9-25	la.eig.pd,la.eig.similar	pd
zy-hard-la-9-26	la.eig.quad,calc.geom.quad	inertia,ortho_trans
zy-hard-la-9-27	la.eig.quad,calc.m.impl	inertia
""".strip()


def parse_rows(text: str) -> dict[str, dict]:
    out: dict[str, dict] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 3:
            raise ValueError(f"bad row: {line!r}")
        qid, kps, facets = parts
        out[qid] = {
            "kp_ids": [x.strip() for x in kps.split(",") if x.strip()],
            "facets": [x.strip() for x in facets.split(",") if x.strip()],
        }
    return out


def all_new() -> dict[str, dict]:
    a = parse_rows(ROWS)
    b = parse_rows(ROWS2)
    overlap = set(a) & set(b)
    if overlap:
        raise SystemExit(f"duplicate ids in rest overlay: {sorted(overlap)[:8]}")
    a.update(b)
    return a


