#!/usr/bin/env python3
"""gen_version.py — 生成 frontend/public/version.js（window.EW_VERSION）。

版本号取 git describe --tags --always --dirty。非 git 时 fallback "dev"。
并给 frontend/index.html 的 data.js / papers.js 打 content-hash 缓存破坏。

用法：python3 scripts/gen_version.py
start.sh 启动前调用。
"""
import hashlib
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "frontend" / "public" / "version.js"
INDEX = ROOT / "frontend" / "index.html"
DATA_JS = ROOT / "web" / "data.js"
PAPERS_JS = ROOT / "web" / "papers.js"


def get_version():
    try:
        v = subprocess.check_output(
            ["git", "describe", "--tags", "--always", "--dirty"],
            cwd=str(ROOT),
            stderr=subprocess.DEVNULL,
        ).decode().strip()
        return v or "dev"
    except Exception:
        return "dev"


def sha256_of_file(path: Path) -> str:
    if not path.exists():
        return "dev"
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()[:16]


def patch_index_html(words_hash: str, papers_hash: str):
    if not INDEX.exists():
        return
    html = INDEX.read_text(encoding="utf-8")
    html = re.sub(
        r'(src="/data\.js)(?:\?v=[^"]*)?(")',
        r"\g<1>?v=" + words_hash + r"\g<2>",
        html,
    )
    html = re.sub(
        r'(src="/papers\.js)(?:\?v=[^"]*)?(")',
        r"\g<1>?v=" + papers_hash + r"\g<2>",
        html,
    )
    INDEX.write_text(html, encoding="utf-8")


def main():
    v = get_version()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "/* auto-generated by scripts/gen_version.py — do not edit */\n"
        f"window.EW_VERSION = {v!r};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} -> {v}")

    words_hash = sha256_of_file(DATA_JS)
    papers_hash = sha256_of_file(PAPERS_JS)
    patch_index_html(words_hash, papers_hash)
    print(f"patched index.html data.js?v={words_hash} papers.js?v={papers_hash}")


if __name__ == "__main__":
    main()
